<?php
/**
 * @author Lukáš Brzák <lukas.brzak@email.cz>
 */

namespace Symfonisti\SonataDemoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NoteRepository extends EntityRepository
{
}
